#!/system/bin/sh
MODDIR=${0%/*}

# Wait for system boot completion
while [ "$(getprop sys.boot_completed)" != "1" ]; do
    sleep 2
done

# Ensure SurfaceFlinger service is responsive
until service check SurfaceFlinger | grep -q "found"; do
    sleep 1
done

LOGFILE="$MODDIR/calibration.log"
echo "[$(date)] MT6789 Color Calibration service starting..." > "$LOGFILE"

# Default User-Approved Ultra Clarity Matrix (R:246, G:250, B:256, Sat:108%)
SF_MATRIX="1.042 0.000 0.000 0.000 0.000 1.018 0.000 0.000 0.000 0.000 1.095 0.000 0.000 0.000 0.000 1.000"
KCAL_RGB="246 250 256"

# Parse JSON config if generated by WebUI
if [ -f "$MODDIR/config.json" ]; then
    echo "[$(date)] Found custom config.json from WebUI" >> "$LOGFILE"
    if command -v jq >/dev/null 2>&1; then
        KCAL_R=$(jq -r '.global.r // 246' "$MODDIR/config.json" 2>/dev/null)
        KCAL_G=$(jq -r '.global.g // 250' "$MODDIR/config.json" 2>/dev/null)
        KCAL_B=$(jq -r '.global.b // 256' "$MODDIR/config.json" 2>/dev/null)
        [ -n "$KCAL_R" ] && KCAL_RGB="$KCAL_R $KCAL_G $KCAL_B"
    fi
fi

apply_sf_matrix() {
    call_args="1"
    for val in $SF_MATRIX; do
        call_args="$call_args f $val"
    done
    service call SurfaceFlinger 1015 i32 $call_args >/dev/null 2>&1
    cmd color_display set-saturation 108 >/dev/null 2>&1
}

apply_kcal() {
    KCAL_NODES="
    /sys/devices/platform/kcal_ctrl.0/kcal
    /sys/module/kcal_val/parameters/rgb
    /sys/class/graphics/fb0/kcal
    /sys/class/graphics/fb0/rgb
    "
    for node in $KCAL_NODES; do
        if [ -f "$node" ]; then
            chmod 664 "$node" 2>/dev/null
            echo "$KCAL_RGB" > "$node" 2>/dev/null
            echo "[$(date)] Applied KCAL RGB ($KCAL_RGB) to $node" >> "$LOGFILE"
            break
        fi
    done
    if [ -f "/sys/devices/platform/kcal_ctrl.0/kcal_enable" ]; then
        echo 1 > "/sys/devices/platform/kcal_ctrl.0/kcal_enable" 2>/dev/null
    fi
}

# Apply on boot
apply_sf_matrix
apply_kcal

# Indestructible Dynamic Event Monitor
(
    while true; do
        logcat -v tag -b events,main SurfaceFlinger:I DisplayFeature:I *:S 2>/dev/null | while read -r line; do
            case "$line" in
                *refresh*|*setRefreshRate*|*displayfeature*|*screen_state*)
                    sleep 0.2
                    apply_sf_matrix
                    ;;
            esac
        done
        sleep 3
    done
) &

# Periodic Watchdog (10s interval)
(
    while true; do
        sleep 10
        apply_sf_matrix
    done
) &
